# .travis.yml
sudo: required
services:
  - docker

before_install:
  - docker build -t jmrhub/react-travis -f dev.Dockerfile .

script:
  - docker run jmrhub/react-travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "grider-react"
  env: "GriderReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-236959176402"
  bucket_path: "grider-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY